AWSTemplateFormatVersion: '2010-09-09'
Description: 'ECS Cluster for Cloud Defender Game'

Parameters:
  Environment:
    Type: String
    Default: dev
    AllowedValues:
      - dev
      - test
      - prod
    Description: Environment name
  
  ClusterName:
    Type: String
    Default: cloud-defender
    Description: Name of the ECS cluster
  
  LogRetentionDays:
    Type: Number
    Default: 30
    Description: Number of days to retain CloudWatch logs

Resources:
  # ECS Cluster
  Cluster:
    Type: AWS::ECS::Cluster
    Properties:
      ClusterName: !Sub '${ClusterName}-${Environment}'
      ClusterSettings:
        - Name: containerInsights
          Value: enabled
      Tags:
        - Key: Name
          Value: !Sub '${ClusterName}-${Environment}'
        - Key: Environment
          Value: !Ref Environment
  
  # CloudWatch Log Group
  LogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub '/ecs/${ClusterName}-${Environment}'
      RetentionInDays: !Ref LogRetentionDays
      Tags:
        - Key: Name
          Value: !Sub '${ClusterName}-${Environment}-logs'
        - Key: Environment
          Value: !Ref Environment
  
  # CloudWatch Dashboard
  Dashboard:
    Type: AWS::CloudWatch::Dashboard
    Properties:
      DashboardName: !Sub '${ClusterName}-${Environment}-dashboard'
      DashboardBody: !Sub |
        {
          "widgets": [
            {
              "type": "metric",
              "x": 0,
              "y": 0,
              "width": 12,
              "height": 6,
              "properties": {
                "metrics": [
                  [ "AWS/ECS", "CPUUtilization", "ClusterName", "${ClusterName}-${Environment}", { "stat": "Average" } ]
                ],
                "period": 300,
                "stat": "Average",
                "region": "${AWS::Region}",
                "title": "CPU Utilization"
              }
            },
            {
              "type": "metric",
              "x": 12,
              "y": 0,
              "width": 12,
              "height": 6,
              "properties": {
                "metrics": [
                  [ "AWS/ECS", "MemoryUtilization", "ClusterName", "${ClusterName}-${Environment}", { "stat": "Average" } ]
                ],
                "period": 300,
                "stat": "Average",
                "region": "${AWS::Region}",
                "title": "Memory Utilization"
              }
            },
            {
              "type": "log",
              "x": 0,
              "y": 6,
              "width": 24,
              "height": 6,
              "properties": {
                "query": "SOURCE '/ecs/${ClusterName}-${Environment}' | fields @timestamp, @message\n| sort @timestamp desc\n| limit 100",
                "region": "${AWS::Region}",
                "title": "Recent Logs",
                "view": "table"
              }
            }
          ]
        }
  
  # CloudWatch Alarms
  CPUAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: !Sub '${ClusterName}-${Environment}-high-cpu'
      AlarmDescription: !Sub 'Alarm if CPU utilization is too high for ${ClusterName}-${Environment} cluster'
      Namespace: AWS/ECS
      MetricName: CPUUtilization
      Dimensions:
        - Name: ClusterName
          Value: !Sub '${ClusterName}-${Environment}'
      Statistic: Average
      Period: 60
      EvaluationPeriods: 3
      Threshold: 80
      ComparisonOperator: GreaterThanThreshold
      TreatMissingData: notBreaching
      Tags:
        - Key: Name
          Value: !Sub '${ClusterName}-${Environment}-cpu-alarm'
        - Key: Environment
          Value: !Ref Environment
  
  MemoryAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: !Sub '${ClusterName}-${Environment}-high-memory'
      AlarmDescription: !Sub 'Alarm if memory utilization is too high for ${ClusterName}-${Environment} cluster'
      Namespace: AWS/ECS
      MetricName: MemoryUtilization
      Dimensions:
        - Name: ClusterName
          Value: !Sub '${ClusterName}-${Environment}'
      Statistic: Average
      Period: 60
      EvaluationPeriods: 3
      Threshold: 80
      ComparisonOperator: GreaterThanThreshold
      TreatMissingData: notBreaching
      Tags:
        - Key: Name
          Value: !Sub '${ClusterName}-${Environment}-memory-alarm'
        - Key: Environment
          Value: !Ref Environment

Outputs:
  ClusterName:
    Description: Name of the ECS cluster
    Value: !Ref Cluster
    Export:
      Name: !Sub '${AWS::StackName}-ClusterName'
  
  ClusterArn:
    Description: ARN of the ECS cluster
    Value: !GetAtt Cluster.Arn
    Export:
      Name: !Sub '${AWS::StackName}-ClusterArn'
  
  LogGroupName:
    Description: Name of the CloudWatch log group
    Value: !Ref LogGroup
    Export:
      Name: !Sub '${AWS::StackName}-LogGroupName'
  
  DashboardName:
    Description: Name of the CloudWatch dashboard
    Value: !Ref Dashboard
    Export:
      Name: !Sub '${AWS::StackName}-DashboardName'
